### ISSUE TITLE
Push and pull NanoBus application to and from an OCI registry

### ISSUE THREAD

**Issue by pkedy** [nanobus/nanobus#15]
This issue proposes the addition of two new subcommands: `nanobus push`, `nanobus pull` and being able to pass an OCI reference to `nanobus run`.

In the application config (`bus.yaml`), there should be enough detail for `nanobus push` to function without having to specify lots of arguments/flags. A few fields can be added to the existing `application` section to accomplish this.

```yaml
application:
  registry: reg.mycompany.com
  org: examples
  id: url-shortener
  version: 0.0.1
  environment: local

package:
  add:
    - ./apex.aidl
    - ./build
    - ./sql
```

In this example, it can be derived that `reg.mycompany.com/examples/url-shortener:0.0.1` is the OCI reference. The CLI would still provide `registry`, `org`, and `applicationId` flags to override what is in the configuration.

This example also has a new `package` section. This is a case where the extensibility of NanoBus can make other functions more complex. The configuration file is added automatically, but it would be really nice if the other contents of the package could be calculated. Since file references exist mostly in configurable resources, the core runtime cannot easily determine the files to include. This means for now, it might be best to make it explicit and iterate on the idea of automatic packaging in the future.

For authentication, a scheme for passing credentials only to their intended host is needed. This could be done using a "flyweight" environment variable pattern. e.g.

```
export OCI_REGISTRIES=MYREG,OTHERREG
export MYREG_HOSTNAME=reg.mycompany.com
export MYREG_USERNAME=myun
export MYREG_PASSWORD=mypw
...
```

`OCI_REGISTRIES` is a comma delimited list of registry names. Each name has corresponding variables to hostname, username, and password. Hostname is used to match the host of the registry being accessed. Only then are the credentials set for the repository client.

**Comment by fawadasaurus** [comment]
I don't think that `nanobus run` is intuitive.  Right now it is just `nanobus` and it looks for a bus.yaml in the PWD.

can it be `nanobus reg.candle.run/myorg/myapp:v0.0.1`?

Unless there are other uses for `run`

**Comment by pkedy** [comment]
@fawadasaurus Actually there are other subcommands now, like `run`, `invoke` so `nanobus run` is already in place. I did try to make `run` the default subcommand, but that was not possible due to the presence of optional arguments. One hack would be to create a separate command that is the default that assumes loading `bus.yaml`. Outside of that there is not much I can do.
