### ISSUE TITLE
Re-assess Makefiles and/or refactor Makefile structure

### ISSUE THREAD

**Issue by jsoverson** [nanobus/nanobus#19]
We've been relying on Makefiles for a long time and `make` has an astounding number of frustrating aspects to it. We need *some* centralized task runner but there isn't a clear alternative.

# Alternatives

- [~~cargo-make~~](https://github.com/sagiegurari/cargo-make)

`cargo-make` adds a lot but still brings with it a number of frustrating parts of make like automatic global configuration.

- [~~just~~](https://github.com/casey/just)

`just` could be great but without a way to include remote justfiles it falls short (tracking issue: https://github.com/casey/just/issues/237)

- [task](https://taskfile.dev/#/)

TBD

**Comment by pkedy** [comment]
Closing after nanobus switch
