### ISSUE TITLE
Poor error message when wafl gets a 404 from OCI registry

### ISSUE THREAD

**Issue by j12naraja** [nanobus/nanobus#40]
**Error received**
*ERROR Failed to fetch OCI bytes: Could not fetch 'reg.candle.run/candle/getting-started:latest': expected value at line 1 column 1*

*wasmflow exited with error: Could not load from location*
*Run with --info, --debug, or --trace for more information.*

As I was going through the getting started guide, I reached the **As a microservice** section. I ran this command:
`wasmflow serve reg.candle.run/candle/getting-started --rpc --rpc-port 8060`
and received the error above.

The output is supposed to be similar to this:

```
2022-06-20T22:16:51  INFO GRPC server bound to 127.0.0.1 on port 8060
2022-06-20T22:16:51  INFO Waiting for ctrl-C
2022-06-20T22:16:51  INFO Starting RPC server
```

**Environment:**
 - macOS
 - Monterey
 - Version 12.4
 - MacBook Pro: Apple M1 Pro, 16gb ram

![Screen Shot 2022-07-05 at 8 21 00 PM](https://user-images.githubusercontent.com/107944482/177463482-26b92794-1615-49e6-9e36-4caacbe4b53e.png)

**Comment by jsoverson** [comment]
The registry server was temporarily unavailable and this issue is fixed but I'm keeping it open to track that the error message needs to be improved.

**Comment by pkedy** [comment]
Closing after nanobus switch
