### ISSUE TITLE
Remove host config from manifests, add a project metadata file (e.g. `wasmflow.toml`)

### ISSUE THREAD

**Issue by jsoverson** [nanobus/nanobus#56]
**Feature request**
We started with host configurations configured side-by-side with flow component definitions in one manifest, but it's not scaling well. Depending on child manifests that include host configurations is confusing. If flow-component manifests are meant to be treated as the same class as compiled code, we should get unrelated configuration out of them.

**Proposal**
Define a project metadata file (e.g. `wasmflow.toml`) that includes

- Version
- Host configuration from current `.wafl` manifests
- A list of `.wafl` files to host.

**This list to be updated as necessary**

**Describe alternatives you've considered**

We've iterated over two versions of the core manifest and have tried to make it work. Recently it's become more clear why it hasn't felt "right" which is what spawned this issue.

**Additional context**

Other proposed features for the project metadata definition:

- A list of tasks and the commands to run (to obviate the `Makefile` for component development)
- Move the "trigger" concept out of manifests and into the project metadata because it pertains to the host, not the flow.
- Bake in the concept of a metadata-lock file for embedding public keys, versions, and schemas of child dependencies.

**Comment by pkedy** [comment]
Closing after nanobus switch
