### ISSUE TITLE
Wafl RPC Invoke to allow hostname(String) instead of forcing IPv4

### ISSUE THREAD

**Issue by fawadasaurus** [nanobus/nanobus#65]
**Is your feature request related to a problem? Please describe.**
I am trying to use the wafl binary as part of a docker-compose system and I need to use the `--address` field to have another docker container's hostname instead of an IP address.  Currently it limits me to use IP address which is unknown until the container is created.

**Propose a solution**
Allow string values here and do not enforce it to be ipv4

**Describe alternatives you've considered**
add a host or hostname field instead of address but that seems redundant.

**Additional context**
None

**Comment by pkedy** [comment]
Closing after nanobus switch
