### ISSUE TITLE
Use connection string instead of address + port.

### ISSUE THREAD

**Issue by fawadasaurus** [nanobus/nanobus#67]
Most protocols that are worthwhile today take url based endpoint and as a developer I just want to throw url in without having to figure out command line options - throwing url at something makes me not need make decisions how to pass things to separate CLI arguments - URLs often also carry other information in parameters.

You can always in the future add further CLI options for protocols that require different scheme but URL should be the default that covers the most.

Most MQs including nats have URL scheme: https://docs.nats.io/using-nats/developer/connecting

Even WebSockets are modelled as ws[s]:// and mqtt mqtt[s]:// as well etc .. 

And yes URL as a tried and trusted standardised scheme supports multiple protocols, encryption / authentication options, connection options as well as other supplied often proprietary protocol / application specific arguments at ease

_Originally posted by @pinkforest in https://github.com/wasmflow/wasmflow/pull/66#issuecomment-1202563181_

**Comment by pkedy** [comment]
Closing after nanobus switch
