### ISSUE TITLE
Iota: Wazero 

### ISSUE THREAD

**Issue by gedw99** [nanobus/nanobus#69]
Wazero ?

it’s nearing V1…
No cgo

**Comment by pkedy** [comment]
@gedw99 Yes, Now that v1.0 is out, NanoBus will upgrade. 🎉

**Comment by gedw99** [comment]
Awesome :)

don’t forget apexlang parser and compiler. It seem to use WAPC, which works with Wazero already I think. 

https://apexlang.io/docs/embedding

**Comment by pkedy** [comment]
@gedw99 Yes. I'm making my rounds to all of these projects :sweat_smile: Thanks!
