### ISSUE TITLE
Sporadic test error: "Error: General error : Port not found or already drained 'output'"

### ISSUE THREAD

**Issue by jsoverson** [nanobus/nanobus#73]
**Describe the bug**
Tests sporadically fail with "Error: General error : Port not found or already drained 'output'"

**Actual behavior**
Tests that normally pass will occasionally fail with the above error.

**Expected behavior**
Tests should never fail.

**To Reproduce**
Can't reproduce consistently.

**Environment:**
 - OS: Mac, Ubuntu
 - Architecture, m1, x86-64
 - Build Version: r8

**Comment by pkedy** [comment]
Closing after nanobus switch
